spring.application.name=e-commerce
server.port=1333


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.url=jdbc:postgresql://localhost:1300/postgres-db


# jpa configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
media.location=E:\\back-end-trying\\fileUpload\\

media.client-path=/media

media.base-uri=http://localhost:1333

#spring.security.user.name=vipha
#spring.security.user.password=12345678
#spring.security.user.roles=STAFF